# Welcome to Jekyll!

# Website settings
title: "LyzandeR"
description: "Theo's blog about Data Science!"
keywords: "Theo, Boutaris, R, Python, blog, Jekyll, github, netlify, Data Science, Spark, Shiny, Web Development"
baseurl: "/"
url: "http://www.lyzander.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Theo'
  first_name: 'Theo'
  last_name: 'Boutaris'
  email: 'theo.boutaris@lyzander.com'
  linkedin_username: 'theoboutaris'
  stackoverflow_username: '4130044/LyzandeR'
  github_username: 'LyzandeR'
  head_img: 'static/img/landing/Theo.jpg'
  desc: 'Theo is a Data Scientist currently residing in the UK. He has a passion for statistics and coding, which naturally led him to follow the Data Science path.
    He is an R evangelist and open source supporter and tries to give back to the community in his free time. He originates from the great city of Thessaloniki in
    Greece. When not coding, he plays football, listens to music or plays Dota2.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: www-lyzander-com
  public_key: LhfwGGSBGmaoYoiabHhb3Xi9vDzu9cLkt5wUtazGOeBaGSNoLzDsaJng7CWoYXmf

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
